name: f_contacter
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  scoped_model: "^0.3.0"
  shared_preferences: "^0.4.3"
  url_launcher: "^4.0.1"
  flutter_search_bar: "^2.0.7"
  flutter_webview_plugin: "^0.2.1+2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/welcome_background.png