name: f_contacter
description: A new Flutter application.
version: 1.0.0+1
environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #RxDart
  rxdart: ^0.22.0
  #Bloc
  flutter_bloc: ^0.15.0
  equatable: ^0.2.6
  #Network
  connectivity: ^0.4.3+1
  http: ^0.12.0+2
  dio: ^2.1.6
  url_launcher: ^5.0.2
  #Preferences
  shared_preferences: ^0.5.2
  #UI
  flutter_search_bar: ^2.0.7
  flutter_webview_plugin: ^0.3.4
  #Images
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.12.4+2
  cached_network_image: ^0.8.0
  photo_view: ^0.3.3
  #Custom widgets
  path_drawing: ^0.4.1
  #List
  queries: ^0.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/welcome_background.png
    - assets/error_network.svg
    - assets/error_other.svg
    - assets/bubble.svg
    - assets/ic_contact.svg
    - assets/ic_status.svg
    - assets/ic_profile.svg
    - assets/ic_phone.svg
    - assets/ic_email.svg
    - assets/user.svg
    - assets/ic_arrow.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-SemiBold.otf
        - asset: fonts/Poppins-Medium.otf
        - asset: fonts/Poppins-Regular.otf
        - asset: fonts/Poppins-Light.otf
